# Test Profile
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never
      data-locations: classpath:static/data-test.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false

app:
  rate-limit:
    enabled: false
