spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      mode: always
      data-locations: classpath:static/data-dev.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
