spring:
  config:
    activate:
      on-profile: test

  sql:
    init:
      mode: always
      data-locations: classpath:data-test.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
