package com.literandltx.reportservice.unit;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.literandltx.reportservice.event.ReportRequestedEvent;
import com.literandltx.reportservice.event.ReportType;
import com.literandltx.reportservice.service.ReportGeneratorService;
import com.literandltx.reportservice.service.strategy.ReportGeneratorStrategy;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class ReportGeneratorServiceTest {

    @Mock
    private ReportGeneratorStrategy pdfStrategy;

    @Mock
    private ReportGeneratorStrategy txtStrategy;

    private ReportGeneratorService reportGeneratorService;

    @BeforeEach
    void setUp() {
        when(pdfStrategy.getReportType()).thenReturn(ReportType.PDF);
        when(txtStrategy.getReportType()).thenReturn(ReportType.TXT);

        reportGeneratorService = new ReportGeneratorService(List.of(pdfStrategy, txtStrategy));
    }

    @Test
    @DisplayName("Should successfully route to the correct strategy and return generated report")
    void shouldGeneratePdfReportSuccessfully() {
        // Arrange
        ReportRequestedEvent event = createEvent(ReportType.PDF);
        byte[] expectedBytes = "pdf-content".getBytes();
        
        when(pdfStrategy.generate(event)).thenReturn(expectedBytes);

        // Act
        byte[] result = reportGeneratorService.generateReport(event);

        // Assert
        assertThat(result)
                .as("The generated bytes should match the strategy's output")
                .isEqualTo(expectedBytes);
        verify(pdfStrategy).generate(event);
    }

    @Test
    @DisplayName("Should successfully route to the correct strategy and return generated report")
    void shouldGenerateTxtReportSuccessfully() {
        // Arrange
        ReportRequestedEvent event = createEvent(ReportType.TXT);
        byte[] expectedBytes = "txt-content".getBytes();

        when(txtStrategy.generate(event)).thenReturn(expectedBytes);

        // Act
        byte[] result = reportGeneratorService.generateReport(event);

        // Assert
        assertThat(result)
                .as("The generated bytes should match the strategy's output")
                .isEqualTo(expectedBytes);
        verify(txtStrategy).generate(event);
    }

    @Test
    @DisplayName("Should throw IllegalArgumentException when strategy is missing for the requested type")
    void shouldThrowExceptionForUnsupportedFormat() {
        // Arrange
        ReportGeneratorService emptyService = new ReportGeneratorService(List.of());
        ReportRequestedEvent event = createEvent(ReportType.PDF);

        // Act & Assert
        assertThatThrownBy(() -> emptyService.generateReport(event))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("Unsupported report format: " + ReportType.PDF);
    }

    private ReportRequestedEvent createEvent(ReportType type) {
        return new ReportRequestedEvent(
                UUID.randomUUID(),
                100L,
                "user@example.com",
                type,
                Map.of("fromDate", "2026-05-01", "toDate", "2026-05-23")
        );
    }
}
